name: vitals_arch
description: Arch components for Visionable projects
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  get_it: ^7.7.0
  vitals_utils:
    path: ../vitals_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  vitals_lint:
    path: ../vitals_lint