name: vitals_lint
description: Dart analyzer settings for Visionable projects
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter_lints: ^4.0.0