name: vitals_sdk_example
description: Demonstrates how to use the vitals_sdk plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.22.0

dependency_overrides:
  uuid: ^4.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  country_icons: ^3.0.0
  i18next:
    path: ../packages/i18next
  intl: ^0.19.0
  auto_route: ^8.2.0
  injectable: ^2.4.2
  window_manager: ^0.3.9
  path_provider: ^2.1.3
  system_tray: ^2.0.3
  realm: ^20.0.0
  flutter_linkify: ^6.0.0
  flutter_text_sniffer: ^4.4.3+5
  vitals_core:
    path: ../packages/vitals_core
  vitals_arch:
    path: ../packages/vitals_arch
  vitals_utils:
    path: ../packages/vitals_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  vitals_lint:
    path: ../packages/vitals_lint
  build_runner: ^2.4.11
  freezed: ^2.5.2
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/vector_images/
    - assets/json/
    - i18next/en-US/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
flutter_intl:
  enabled: true
  main_locale: en_US